spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

      routes:
        - id: setstatus_route
          uri: http://localhost:8088/
          filters:
            - name: SetStatus
              args:
                status: 401
          predicates:
            - Path=/clients/**
